name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18

    - name: Build generator
      run: go build -v ./...
      working-directory: ./generator

    - name: Generate update data
      run: generator/airmessage-update
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.3.3
      with:
        branch: gh-pages
        folder: output
